#!/system/bin/sh                                                           
# Make sure ApkCLI Directories are made                                    
mkdir -p /sdcard/.apkcli/APK/
mkdir -p /sdcard/.apkcli/tmp/txz
mkdir -p /sdcard/.apkcli/savedtxz

# Prompt the user
echo "Requested Package: F-Droid
Repository: ApkCLI Official Repos
Repository Link: https://github.com/Bikoil/ApkCLIRepos
! | Do you want to install this package? [Y/n]: \c"
read answer                                                                

# If the answer is empty, set it to 'y'
if [ -z "$answer" ]; then
   answer="y"
fi

# Convert the answer to lowercase
answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')

# Check the user's input
if [ "$answer" = "y" ] || [ "$answer" = "yes" ]; then
    echo "Installing the package..."
    echo "! | Fetching Package from https://github.com/Bikoil/ApkCLIRepos..."
    # Install the txz file
    curl -o /sdcard/.apkcli/tmp/txz/fdroid.txz https://raw.githubusercontent.com/Bikoil/ApkCLIRepos/main/Packages/fdroid.txz
    # Another prompt
    echo "! | Compressed file installed! Would you like to keep the 'txz' file? [y/N]: \c"
    read answer

    if [ -z "$answer" ]; then
       answer="n"
    fi

    answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
    if [ "$answer" = "y" ] || [ "$answer" = "yes" ]; then
       cp /sdcard/.apkcli/tmp/txz/fdroid.txz /sdcard/.apkcli/savedtxz
       echo "txz File has been saved to /sdcard/.apkcli/savedtxz/"
    fi

    # Starts extracting the txz file
    echo "Extracting the file..."
    tar -xJf /sdcard/.apkcli/tmp/txz/fdroid.txz -C /sdcard/.apkcli/APK/
    # Check if the user is shell so if they have enough privileges
    if [ "$USER" = "shell" ]; then
        echo "User is shell, Installing using pm..."
        pm install /sdcard/.apkcli/APK/F-Droid.apk
    elif echo "$USER" | grep -qE '^u0_'; then
        echo "User starts with u0_, Redirecting to package manager..."
        am start -a android.intent.action.VIEW -d file:///sdcard/.apkcli/APK/F-Droid.apk -t application/vnd.android.package-archive
    elif [ "$USER" = "root" ]; then
        echo "User is root, Installing using pm..."
        pm install /sdcard/.apkcli/APK/F-Droid.apk
    else
        echo "User is unknown, Using pm by default..."
        pm install /sdcard/.apkcli/APK/F-Droid.apk
    fi

    rm /sdcard/.apkcli/tmp/txz/fdroid.txz
else
    echo "X | Installation aborted."
fi
