#!/system/bin/sh                                                           
# Make sure ApkCLI Directories are made                                    
mkdir -p /sdcard/.apkcli/APK/
mkdir -p /sdcard/.apkcli/tmp/tgz
mkdir -p /sdcard/.apkcli/savedtgz
# Variables
apkdir="/sdcard/.apkcli/APK"
apkcli="/sdcard/.apkcli/"

# Prompt the user
echo "Requested Package: F-Droid
Repository: ApkCLI Official Repos
Repository Link: https://github.com/Bikoil/ApkCLIRepos
! | Do you want to install this package? [Y/n]: \c"
read answer                                                                

# If the answer is empty, set it to 'y'
if [ -z "$answer" ]; then
   answer="y"
fi

# Convert the answer to lowercase
answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')

# Check the user's input
if [ "$answer" = "y" ] || [ "$answer" = "yes" ]; then
    echo "Installing the package..."
    echo "! | Fetching Package from https://github.com/Bikoil/ApkCLIRepos..."
    # Install the tgz file
    curl -o $apkcli/tmp/tgz/fdroid.tgz https://raw.githubusercontent.com/Bikoil/ApkCLIRepos/main/Packages/fdroid.tgz
    # Another prompt
    echo "! | Compressed file installed! Would you like to keep the 'tgz' file? [y/N]: \c"
    read answer

    if [ -z "$answer" ]; then
       answer="n"
    fi

    answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
    if [ "$answer" = "y" ] || [ "$answer" = "yes" ]; then
       cp $apkcli/tmp/tgz/fdroid.tgz /sdcard/.apkcli/savedtgz
       echo "tgz File has been saved to /sdcard/.apkcli/savedtgz/"
    fi

    # Starts extracting the tgz file
    echo "Extracting the file..."
    tar -xzf $apkcli/tmp/tgz/fdroid.tgz -C $apkcli/APK/
    # Check if the user is shell so if they have enough privileges
    if [ "$USER" = "shell" ]; then
        echo "User is shell, Installing using pm..."
        pm install $apkdir/F-Droid.apk
    elif echo "$USER" | grep -qE '^u0_'; then
        echo "User is u0_, Using termux-open..."
        termux-open $apkdir/F-droid.apk
    elif [ "$USER" = "root" ]; then
        echo "User is root, Installing using pm..."
        pm install $apkdir/APK/F-Droid.apk
    else
        echo "User is unknown, Using pm by default..."
        pm install $apkdir/F-Droid.apk
    fi

    rm $apkcli/tmp/tgz/fdroid.tgz
else
    echo "X | Installation aborted."
fi
